@startuml
title AS-IS WarmHouse Context Diagram


!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Пользователь системы умного дома")
Person(admin, "Admin", "Администратор, подключающий пользователей к системе умного дома")

System(WarmHouseSystem, "WarmHouse System", "Умный дом")

System_Ext(device, "Системы отопления", "Системы отопления, установленные в домах пользователей (обогреватели с датчиками)")


Rel(user, WarmHouseSystem, "Использует систему (Вкл/вкл обогреватели, получение текущей температуры)")
Rel(admin, WarmHouseSystem, "Добавляет пользователей в систему")
Rel(WarmHouseSystem, device, "Получает данные от датчика и отправляет сигналы на ВКЛ/ВЫКЛ обогревателя")


@enduml