openapi: 3.0.4
info:
  title: Swagger WarmHome - OpenAPI 3.0
  version: 1.0.12

tags:
  - name: device

paths:
  /device:
    post:
      tags:
        - device
      description: Adding new device.
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /device/{device_id}:
    get:
      tags:
        - device
      description: Returns a single device by ID.
      parameters:
        - name: device_id
          in : path
          description: Device ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '404':
          description: Pet not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      tags:
        - device
      description: Update an existing device by ID.
      parameters:
        - name: device_id
          in : path
          description: Device ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update an existing device
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '400':
          description: Invalid ID supplied
        '404':
          description: Device not found
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      tags:
        - device
      description: Returns a single device by it's ID
      parameters:
        - name: device_id
          in : path
          description: Device ID
          required: true
          schema:
            type: integer
            format: uint64
      responses:
        '200':
          description: Successful operation
        '404':
          description: Device not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    Device:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        serial_number:
          type: string
          description: Serial nuber of device
          example: AA1234567890AA
        user_id:
          type: integer
          format: int64
          example: 12345
      required:
        - id
        - serial_number
